### ISSUE TITLE
Review if/when/how to upgrade Virtuoso

### ISSUE THREAD

**Issue by ColmMassey** [DigitalCommons/open-data#38]
Start by noting motivations here.
https://github.com/SolidarityEconomyAssociation/open-data-and-maps/issues/150#issuecomment-655444870

**Comment by wu-lee** [comment]
Regarding "How"... Since .deb packages for Ubuntu newer than opensource-virtuoso 0.6.1 seem to be unobtainable, checking around:
- Arch Linux has Virtuoso 7.2 in the user repository [here][1] -  however this is a user contribution so not sure of the quality; also Arch Linux is a new and different beast to Ubuntu. It would require altering our Ansible deployment script. Upgrades will be the responsibility of Arch's package management.
- OpenLink have a [Docker image][2] for the open-source Virtuoso 7.2 (and the enterprise editions 8.3 and 7.2 if you have a licence). It may require altering our Ansible deployment script significantly, probably safer than switching to Arch. Ubuntu's package manager / `apt upgrade` won't know about this app.
- A third alternative is a raw install of the [OpenLink source][4] - I've had bad experiences with 3rd party installers and don't really trust them, so avoid them whenever possible. `apt upgrade` won't know about this app, and 3rd party installers may do who-knows what and leave junk lying around the filesystem in undocumented places. Lack of a distro-specific package is generally an indicator of corner-cutting / lack of resources / lack of know-how.
- Fourth is to use [fpm][3] or something to create our own .deb package from the built source. Building packages are a bit of a PITA, that tool's called "F-ing package management" for a reason; it makes life a bit simpler. `apt upgrade` will know about this app but we will have to provide new versions ourselves.

Of these,I'd probably trust the Docker image most, and it is probably fairly straightforward to deploy (with Ansible) and use, so long as we are happy with Docker. Docker adds some complexity but I hope not *too* much...

[1]: https://aur.archlinux.org/packages/virtuoso/
[2]: https://community.openlinksw.com/t/virtuoso-enterprise-edition-docker-quick-start-guide/285
[3]: https://github.com/jordansissel/fpm
[4]: http://docs.openlinksw.com/virtuoso/virtuosoinstallunixpedescr/

**Comment by ColmMassey** [comment]
About time we had a go at this again. Needed for efficient inferencing.

**Comment by ColmMassey** [comment]
Have we actually shut down sea-0? In not we could test it there.
